const WORDS = [
  'serendipity',
  'eloquent',
  'resilient',
  'curious',
  'genuine',
  'meticulous',
  'candid',
  'vivid',
  'humble',
  'witty',
  'bold',
  'calm',
  'keen',
  'lucid',
  'nimble',
  'poised',
  'subtle',
  'crisp',
  'warm',
  'frank',
  'grit',
  'rizz',
  'delulu',
  'vibes',
  'chill',
  'spark',
  'glow',
  'hustle',
  'flourish',
  'nurture',
  'savor',
  'ponder',
  'wander',
  'linger',
  'embrace',
  'unfold',
  'kindle',
  'soothe',
  'thrive',
  'belong',
  'articulate',
  'concise',
  'nuanced',
  'pragmatic',
  'empathy',
  'integrity',
  'gratitude',
  'patience',
  'courage',
  'clarity',
  'nuance',
  'insight',
  'wonder',
  'delight',
  'solace',
  'reverie',
  'ephemeral',
  'luminous',
  'serene',
  'ardent',
  'tenacious',
  'whimsical',
  'earnest',
  'fervent',
  'plucky',
  'zesty',
  'mellow',
  'breezy',
  'grounded',
  'open-minded',
  'break the ice',
  'on the fence',
  'food for thought',
  'silver lining',
  'rule of thumb',
  'spill the tea',
  'hit the ground running',
  'read the room',
  'cut to the chase',
  'think on your feet',
  'speak up',
  'show up',
  'lean in',
  'let it land',
  'hold space',
  'take a beat',
  'keep it real',
  'say the quiet part',
  'make it land',
  'own it',
  'perspicacious',
  'ubiquitous',
  'ambivalent',
  'pragmatic',
  'succinct',
  'astute',
  'deft',
  'apt',
  'wry',
  'sly',
  'coy',
  'brisk',
  'snappy',
  'punchy',
  'vibe check',
  'main character',
  'low-key',
  'high-key',
  'no cap',
  'bet',
  'periodt',
  'slay',
  'iconic',
  'unhinged',
  'based',
  'mid',
  'ate',
  'understood the assignment',
  'touch grass',
  'it hits different',
  'living rent free',
  'caught lacking',
  'say less',
  'respectfully',
  'with love',
  'in a good way',
  'not gonna lie',
  'to be fair',
  'fair enough',
  'that tracks',
  'makes sense',
  'point taken',
  'well put',
  'nicely said',
]

export function todayKey(now = new Date()): string {
  const y = now.getFullYear()
  const m = String(now.getMonth() + 1).padStart(2, '0')
  const d = String(now.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

function hash(value: string): number {
  let n = 2166136261
  for (let i = 0; i < value.length; i++) {
    n ^= value.charCodeAt(i)
    n = Math.imul(n, 16777619)
  }
  return n >>> 0
}

export function pickWordOfTheDay(userId: string, date: string, owned: Set<string>): string {
  const start = hash(`${date}:${userId}`) % WORDS.length
  for (let i = 0; i < WORDS.length; i++) {
    const word = WORDS[(start + i) % WORDS.length]
    if (!owned.has(word.toLowerCase())) return word
  }
  return WORDS[start]
}
